sudo: required
services: 
  - docker

scripts:
  - docker build -t muhammadwaleed1989/node .
  - docker images muhammadwaleed1989/node


before_deploy:
  - docker login -u muhammadwaleed1989 -p NewYear@@2020

deploy:
  provider: script
  script: docker push muhammadwaleed1989/node
  on:
    branch: master
