sudo: required
services: 
  - docker

scripts:
  - docker build -t node .
  - docker images node

before_deploy:
  - docker login -u muhammadwaleed1989 -p NewYear@@2020

deploy:
  provider: script
  script: docker push node
  on:
    branch: master