sudo: required
services: 
  - docker

scripts:
  - docker build -t node1 .
  - docker images node1


before_deploy:
  - docker login -u MuhammadWaleed1989 -p NewYear@@2020

deploy:
  provider: script
  script: docker push node1
  on:
    branch: master
